function accept = confirmation_dialog(subNum, session)

session_msg = {'first','second','third','fourth','fifth','sixth','seventh'};
resp = questdlg({['Your subject number is ' subNum '.'], ...
    ['This is your ' session_msg{session} ' session.'], ...
    '', ...
    'Is this correct?'}, ...
    'Confirm Subject Info', ...
    'No', 'Yes', 'No');
accept = strcmp(resp, 'Yes');
end